[package]
name = "os-locale"
version = "0.1.0"
authors = ["i509VCB <git@i509.me>"]
edition = "2018"

[dependencies]

# Platform dependencies
[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"
features = [
    "minwindef", # WORD
    "winnls", # winnls.h
    "winnt" # LANGID
]

[target.'cfg(windows)'.dependencies.libc]
version = "0.2.82" # wcslen

[target.'cfg(target_os = "macos")'.dependencies.objc]
version = "0.2.7"

[target.'cfg(target_os = "macos")'.dependencies.objc-foundation]
version = "0.1.1"
